name: script_projeto_flutter
description: Aplicativo Analisador de Texto com Login e Cadastro (MVVM)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Gerenciamento de estado (ViewModels)
  provider: ^6.0.5

  # Banco de dados local
  sqflite: ^2.3.0
  path: ^1.9.0

  # Hash de senha
  crypto: ^3.0.3

  # MÃ¡scara para CPF e outros campos
  mask_text_input_formatter: ^2.5.0

  # Date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
